project_id = "qytorkjmzxscyaefkhnk"

[functions.strava-config]
verify_jwt = false

[functions.strava-auth]
verify_jwt = true

[functions.strava-sync]
verify_jwt = true

[functions.strava-sync-test]
verify_jwt = true

[functions.process-training-sessions]
verify_jwt = true

[functions.garmin-config]
verify_jwt = false

[functions.garmin-auth]
verify_jwt = true

[functions.garmin-sync]
verify_jwt = true

[functions.garmin-webhook]
verify_jwt = false

[functions.garmin-webhook-registration]
verify_jwt = true

[functions.recalculate-backfill-processed-activities]
verify_jwt = true